[[imports]]
    path = "github.com/gethugothemes/hugo-modules/gallery-slider"

[[imports]]
    path = 'github.com/hugomods/search'

[[imports]]
    path = 'github.com/hugomods/icons/vendors/bootstrap'
[[imports]]
    path = 'github.com/hugomods/images'
[[imports]]
    path = 'github.com/hugomods/bootstrap'
[[imports]]
    path = 'github.com/hugomods/katex'