# THIS IS AN EXAMPLE ON HOW YOU SHOULD CONFIGURE YOUR hugo.toml
# See this hugo.toml in action at https://github.com/1bl4z3r/hermit-V2/blob/staging/hugo.toml
# Example Site is Staging branch, acessible at https://github.com/1bl4z3r/hermit-V2/tree/staging
# To see what each config does, refer to https://1bl4z3r.github.io/hermit-V2/en/posts/explaining-configs/
# Open Issue or Pull Request at https://github.com/1bl4z3r/hermit-V2

baseURL = "https://albertoreineri.it"
defaultContentLanguage = "it"
defaultContentLanguageInSubdir = false
theme = "hermit-v2"
languageCode = "it-it"


[languages]
 [languages.it]
   title = 'Alberto Reineri'
   languageName = "ITA"
   #flag = '<svg xmlns="http://www.w3.org/2000/svg" id="flag-icons-it" viewBox="0 0 640 480"><g fill-rule="evenodd" stroke-width="1pt"><path fill="#fff" d="M0 0h640v480H0z"/><path fill="#009246" d="M0 0h213.3v480H0z"/><path fill="#ce2b37" d="M426.7 0H640v480H426.7z"/></g></svg>'
   contentDir = "content/it"
   [languages.it.params]
     homeSubtitle = "Web Developer & Sys Admin"
     flagIcon = 'it'
   weight = 1
 [languages.en]
   title = 'Alberto Reineri'
   languageName = "ENG"
   #flag = '<svg xmlns="http://www.w3.org/2000/svg" id="flag-icons-sh" viewBox="0 0 640 480"><path fill="#012169" d="M0 0h640v480H0z"/><path fill="#FFF" d="m75 0 244 181L562 0h78v62L400 241l240 178v61h-80L320 301 81 480H0v-60l239-178L0 64V0z"/><path fill="#C8102E" d="m424 281 216 159v40L369 281zm-184 20 6 35L54 480H0zM640 0v3L391 191l2-44L590 0zM0 0l239 176h-60L0 42z"/><path fill="#FFF" d="M241 0v480h160V0zM0 160v160h640V160z"/><path fill="#C8102E" d="M0 193v96h640v-96zM273 0v480h96V0z"/></svg>'
   contentDir = 'content/en'
   [languages.en.params]
     homeSubtitle = "Web Developer & Sys Admin"
     flagIcon = 'en'
   weight = 2
#  [languages.it]
#    title = 'CHANGE ME(IT)'
#    [languages.it.params]
#      homeSubtitle = "CHANGE ME"
#    weight = 3


title = "Alberto Reineri"
# enableGitInfo = true

pygmentsCodefences = true
pygmentsUseClasses = true
#hasCJKLanguage = true

rssLimit = 10

copyright = "Alberto Reineri"
enableEmoji = true

# googleAnalytics = "G-9MQ20QPDEM"
disqusShortname = "albertoreineri-it"

[params.author]
name = "Alberto Reineri"
about = ""

[blackfriday]
# hrefTargetBlank = true
# noreferrerLinks = true
# nofollowLinks = true

[taxonomies]
category = 'categories'
tag = 'tags'
argomenti = "argomenti"
raccolte = "raccolte"
# Categories are disabled by default.
# category = "categories"

[params]
dateform = "Jan 2, 2006"
# dateformShort = "Jan 2"
# dateformNum = "2006-01-02"
# dateformNumTime = "2006-01-02 15:04 -0700"
# dateform = "2/01/2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"

# description = "CHANGE ME SITE DESCRIPTION"
# images = [""]
themeColor = "#494f5c"

#homeSubtitle = "CHANGE ME HOME SUBTITLE"
footerCopyright = "Alberto Reineri"
# bgImg = ""
# gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

justifyContent = false

relatedPosts = true
code_copy_button = true

homeSubtitlePrinter = true
scrollToTop = true
global_mathjax = false
readTime = true
readTimeSeparator = "|"
# legacyLayout = false
shareSocial = true
# googleTagManager = "GTM-XXXXXXXX"
# tagSymbol = "#"
# categorySymbol = "⊲"

# [[params.socialLinks]]
# name = "youtube"
# url = "https://www.youtube.com/@albydev2149"

# [[params.socialLinks]]
# name = "spotify"
# url = "https://open.spotify.com/show/546eUw3PsRI1HUGbBUeghC"

[[params.socialLinks]]
name = "github"
url = "https://github.com/albertoreineri"
[[params.socialLinks]]
name = "youtube"
url = "https://github.com/albertoreineri"

[menu]
[[menu.main]]
name = "About"
url = "about/"
weight = 10

[[menu.main]]
name = "Servizi"
url = "servizi/"
weight = 11

[[menu.main]]
name = "Portfolio"
url = "portfolio/"
weight = 12

[[menu.main]]
name = "Blog"
url = "blog/"
weight = 30

[[menu.main]]
name = "Contatti"
url = "contatti/"
weight = 40

[[menu.footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 10

# [[menu.footer]]
# name = "Extra"
# url = "extra/"
# weight = 20
# TODO:
# - Pagina html per portfolio e contatti
# - rileggere articoli e guide e correggere

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


# [module]
#   [module.hugoVersion]
#     extended = false
#     min = "0.121.1"
#   [[module.imports]]
#     path = "github.com/gethugothemes/hugo-modules/gallery-slider"


[[params.plugins.css]]
link = "plugins/glightbox/glightbox.css"

[[params.plugins.js]]
link = "plugins/glightbox/glightbox.js"
[[params.plugins.js]]
link = "js/gallery-slider.js"

[outputs]
  home = ['HTML', 'RSS', 'SearchIndex']

[permalinks]
  blog = '/blog/:title/'